import type {
  ApplicationRow,
  ConversationRow,
  HelperDocumentRow,
  HelperProfileRow,
  MessageRow,
  NotificationRow,
  OfferRow,
  OrganizationProfileRow,
  ProfileRow,
  SavedOfferRow,
} from '$lib/types/database';

// All portfolio-demo data is fictional. Dates are derived from the visitor's
// current day so upcoming assignments and calendar views stay useful over time.
const baseDay = new Date();
baseDay.setHours(12, 0, 0, 0);

function atDays(offset: number, hour = 12): string {
  const date = new Date(baseDay);
  date.setDate(date.getDate() + offset);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
}

function dateOnly(offset: number): string {
  return atDays(offset).slice(0, 10);
}

const createdAt = atDays(-240);
const updatedAt = atDays(-2);

export const DEMO_IDS = {
  helper: 'profile-helper-anna',
  helperBernd: 'profile-helper-bernd',
  helperClara: 'profile-helper-clara',
  org: 'profile-org-sonnenschein',
  orgBunteStadt: 'profile-org-bunte-stadt',
} as const;

export const profiles: ProfileRow[] = [
  {
    id: DEMO_IDS.helper,
    user_id: 'demo-user-helper',
    role: 'helper',
    status: 'active',
    display_name: 'Anna Helferin',
    slug: 'anna-helferin',
    avatar_url: null,
    bio: 'Ich helfe gerne bei Sport-, Bildungs- und Sozialeinsätzen in meiner Umgebung.',
    city: 'Berlin',
    postal_code: '10115',
    country_code: 'DE',
    phone: null,
    website_url: null,
    average_rating: 4.9,
    rating_count: 12,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: DEMO_IDS.helperBernd,
    user_id: 'demo-user-bernd',
    role: 'helper',
    status: 'active',
    display_name: 'Bernd Beispiel',
    slug: 'bernd-beispiel',
    avatar_url: null,
    bio: 'Erfahrener Eventhelfer und Fahrer.',
    city: 'Berlin',
    postal_code: '10117',
    country_code: 'DE',
    phone: null,
    website_url: null,
    average_rating: 4.7,
    rating_count: 8,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: DEMO_IDS.helperClara,
    user_id: 'demo-user-clara',
    role: 'helper',
    status: 'active',
    display_name: 'Clara Code',
    slug: 'clara-code',
    avatar_url: null,
    bio: 'IT-affin, gerne digitale Aufgaben oder Übersetzungen.',
    city: 'Hamburg',
    postal_code: '20095',
    country_code: 'DE',
    phone: null,
    website_url: null,
    average_rating: 5,
    rating_count: 4,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: DEMO_IDS.org,
    user_id: 'demo-user-org',
    role: 'organization',
    status: 'active',
    display_name: 'SV Sonnenschein e.V.',
    slug: 'sv-sonnenschein',
    avatar_url: null,
    bio: 'Fiktiver Sportverein für Jugend, Familie und ein lebendiges Miteinander.',
    city: 'Berlin',
    postal_code: '10115',
    country_code: 'DE',
    phone: null,
    website_url: null,
    average_rating: 4.8,
    rating_count: 24,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: DEMO_IDS.orgBunteStadt,
    user_id: 'demo-user-bunte-stadt',
    role: 'organization',
    status: 'active',
    display_name: 'Initiative Bunte Stadt',
    slug: 'initiative-bunte-stadt',
    avatar_url: null,
    bio: 'Fiktive Initiative für Stadtteilarbeit und Integration.',
    city: 'Hamburg',
    postal_code: '20095',
    country_code: 'DE',
    phone: null,
    website_url: null,
    average_rating: 5,
    rating_count: 7,
    created_at: createdAt,
    updated_at: updatedAt,
  },
];

export const helperProfiles: HelperProfileRow[] = [
  {
    profile_id: DEMO_IDS.helper,
    date_of_birth: '1995-04-18',
    skills: ['Event', 'Soziales', 'Erste Hilfe'],
    languages: ['Deutsch', 'Englisch'],
    availability_note: 'Wochenenden bevorzugt.',
    has_drivers_license: true,
    has_car: true,
    emergency_contact_name: null,
    emergency_contact_phone: null,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    profile_id: DEMO_IDS.helperBernd,
    date_of_birth: '1988-09-02',
    skills: ['Fahren', 'Logistik', 'Event'],
    languages: ['Deutsch'],
    availability_note: 'Abends und am Wochenende.',
    has_drivers_license: true,
    has_car: true,
    emergency_contact_name: null,
    emergency_contact_phone: null,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    profile_id: DEMO_IDS.helperClara,
    date_of_birth: '1998-01-15',
    skills: ['IT', 'Übersetzung', 'Remote'],
    languages: ['Deutsch', 'Englisch', 'Spanisch'],
    availability_note: 'Flexibel und remote.',
    has_drivers_license: false,
    has_car: false,
    emergency_contact_name: null,
    emergency_contact_phone: null,
    created_at: createdAt,
    updated_at: updatedAt,
  },
];

export const organizationProfiles: OrganizationProfileRow[] = [
  {
    profile_id: DEMO_IDS.org,
    organization_type: 'club',
    legal_name: 'SV Sonnenschein e.V. (Demodaten)',
    registration_number: null,
    tax_id: null,
    contact_person_name: 'Maria Muster',
    contact_email: null,
    contact_phone: null,
    is_verified: true,
    verified_at: atDays(-180),
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    profile_id: DEMO_IDS.orgBunteStadt,
    organization_type: 'initiative',
    legal_name: 'Initiative Bunte Stadt (Demodaten)',
    registration_number: null,
    tax_id: null,
    contact_person_name: 'Tom Muster',
    contact_email: null,
    contact_phone: null,
    is_verified: true,
    verified_at: atDays(-160),
    created_at: createdAt,
    updated_at: updatedAt,
  },
];

function offer(
  id: string,
  organizationProfileId: string,
  data: Partial<OfferRow> & Pick<OfferRow, 'title' | 'description' | 'offer_type' | 'status'>,
): OfferRow {
  return {
    id,
    organization_profile_id: organizationProfileId,
    category: null,
    skills_required: [],
    min_age: 16,
    max_helpers: null,
    accepted_helpers_count: 0,
    location_name: null,
    street: null,
    postal_code: null,
    city: null,
    country_code: 'DE',
    is_remote: false,
    starts_at: null,
    ends_at: null,
    application_deadline: null,
    is_binding: false,
    requires_documents: false,
    published_at: atDays(-10),
    completed_at: null,
    cancelled_at: null,
    created_at: atDays(-30),
    updated_at: updatedAt,
    ...data,
  };
}

export const offers: OfferRow[] = [
  offer('offer-sommerfest', DEMO_IDS.org, {
    title: 'Aufbau Sommerfest',
    description:
      'Wir suchen Unterstützung beim Aufbau von Pavillons, Tischen und Bänken sowie bei der Essensausgabe.',
    offer_type: 'single_event',
    status: 'published',
    category: 'event',
    skills_required: ['Event', 'Logistik'],
    max_helpers: 8,
    accepted_helpers_count: 1,
    city: 'Berlin',
    postal_code: '10115',
    location_name: 'Vereinsgelände am Stadtpark',
    starts_at: atDays(14, 8),
    ends_at: atDays(14, 16),
    application_deadline: atDays(10, 18),
  }),
  offer('offer-kindertraining', DEMO_IDS.org, {
    title: 'Wöchentliches Kindertraining',
    description: 'Unterstützung beim wöchentlichen Fußballtraining für Kinder von 8 bis 12 Jahren.',
    offer_type: 'recurring_event',
    status: 'published',
    category: 'sport',
    skills_required: ['Sport', 'Soziales'],
    max_helpers: 3,
    accepted_helpers_count: 1,
    city: 'Berlin',
    location_name: 'Sportplatz Sonnenschein',
    starts_at: atDays(7, 16),
    ends_at: atDays(7, 18),
  }),
  offer('offer-tafel', DEMO_IDS.orgBunteStadt, {
    title: 'Tafel-Ausgabe am Freitag',
    description: 'Sortieren, Packen und Ausgeben von Lebensmittelkisten im Stadtteiltreff.',
    offer_type: 'single_event',
    status: 'published',
    category: 'social',
    skills_required: ['Soziales', 'Logistik'],
    max_helpers: 6,
    city: 'Hamburg',
    location_name: 'Stadtteiltreff Nord',
    starts_at: atDays(4, 14),
    ends_at: atDays(4, 18),
    application_deadline: atDays(2, 18),
  }),
  offer('offer-cleanup', DEMO_IDS.org, {
    title: 'Park-Cleanup Kiezrunde',
    description: 'Gemeinsame Müllsammelaktion mit anschließender Materialrückgabe.',
    offer_type: 'single_event',
    status: 'published',
    category: 'environment',
    skills_required: ['Outdoor', 'Teamwork'],
    max_helpers: 12,
    city: 'Berlin',
    location_name: 'Volkspark',
    starts_at: atDays(21, 10),
    ends_at: atDays(21, 13),
    application_deadline: atDays(18, 18),
  }),
  offer('offer-lesepaten', DEMO_IDS.orgBunteStadt, {
    title: 'Lesepaten-Nachmittag',
    description: 'Vorlesen und kleine Sprachspiele für Grundschulkinder im offenen Treff.',
    offer_type: 'recurring_event',
    status: 'published',
    category: 'education',
    skills_required: ['Bildung', 'Kinder'],
    max_helpers: 4,
    city: 'Hamburg',
    location_name: 'Offener Treff Altona',
    starts_at: atDays(10, 15),
    ends_at: atDays(10, 17),
    application_deadline: atDays(6, 18),
  }),
  offer('offer-kuechenteam', DEMO_IDS.orgBunteStadt, {
    title: 'Morgen: Küchenteam im Stadtteiltreff',
    description: 'Essensausgabe vorbereiten, Gäste begrüßen und beim Aufräumen helfen.',
    offer_type: 'single_event',
    status: 'published',
    category: 'social',
    skills_required: ['Küche', 'Soziales'],
    max_helpers: 3,
    accepted_helpers_count: 1,
    city: 'Hamburg',
    location_name: 'Stadtteiltreff Nord',
    starts_at: atDays(1, 9),
    ends_at: atDays(1, 13),
    application_deadline: atDays(0, 20),
  }),
  offer('offer-gartenaktion', DEMO_IDS.org, {
    title: 'Gemeinschaftsgarten fit für den Frühling',
    description:
      'Beete vorbereiten, Wege freiräumen und gemeinsam neue Kräuter für den Nachbarschaftsgarten pflanzen.',
    offer_type: 'single_event',
    status: 'published',
    category: 'environment',
    skills_required: ['Garten', 'Teamwork'],
    max_helpers: 10,
    city: 'Berlin',
    location_name: 'Gemeinschaftsgarten am Kanal',
    starts_at: atDays(17, 10),
    ends_at: atDays(17, 15),
    application_deadline: atDays(14, 18),
  }),
  offer('offer-webseite', DEMO_IDS.orgBunteStadt, {
    title: 'Übersetzung Webseite EN',
    description: 'Übersetzung einer fiktiven Vereinswebseite ins Englische, etwa fünf Seiten Text.',
    offer_type: 'digital_task',
    status: 'completed',
    category: 'it',
    skills_required: ['Übersetzung', 'Remote'],
    max_helpers: 1,
    accepted_helpers_count: 1,
    is_remote: true,
    starts_at: atDays(-30),
    ends_at: atDays(-20),
    application_deadline: atDays(-32),
    completed_at: atDays(-20),
  }),
  offer('offer-seniorencafe', DEMO_IDS.org, {
    title: 'Seniorencafé Begleitung',
    description: 'Gäste begrüßen, Kaffee ausgeben und beim Abbau unterstützen.',
    offer_type: 'single_event',
    status: 'completed',
    category: 'social',
    skills_required: ['Soziales', 'Gastfreundschaft'],
    max_helpers: 5,
    accepted_helpers_count: 1,
    city: 'Berlin',
    location_name: 'Nachbarschaftshaus Mitte',
    starts_at: atDays(-18, 14),
    ends_at: atDays(-18, 17),
    application_deadline: atDays(-25),
    completed_at: atDays(-18, 17),
  }),
  offer('offer-nachhilfe-draft', DEMO_IDS.org, {
    title: 'Nachhilfe für Jugendliche',
    description: 'Flexible Nachhilfe in Mathematik, Deutsch oder Englisch nach Absprache.',
    offer_type: 'flexible_task',
    status: 'draft',
    category: 'education',
    skills_required: ['Bildung', 'Soziales'],
    max_helpers: 2,
    city: 'Berlin',
    published_at: null,
  }),
];

function application(
  id: string,
  offerId: string,
  helperProfileId: string,
  data: Partial<ApplicationRow> & Pick<ApplicationRow, 'status'>,
): ApplicationRow {
  return {
    id,
    offer_id: offerId,
    helper_profile_id: helperProfileId,
    motivation_text: null,
    organization_note: null,
    helper_message: null,
    submitted_at: atDays(-4),
    accepted_at: null,
    rejected_at: null,
    withdrawn_at: null,
    completed_at: null,
    created_at: atDays(-4),
    updated_at: updatedAt,
    ...data,
  };
}

export const applications: ApplicationRow[] = [
  application('application-anna-sommerfest', 'offer-sommerfest', DEMO_IDS.helper, {
    status: 'submitted',
    motivation_text: 'Ich bin am Wochenende verfügbar und packe gerne mit an.',
    helper_message: 'Bis bald!',
    submitted_at: atDays(-1),
  }),
  application('application-bernd-sommerfest', 'offer-sommerfest', DEMO_IDS.helperBernd, {
    status: 'accepted',
    motivation_text: 'Ich bringe Erfahrung in Logistik und Veranstaltungsaufbau mit.',
    submitted_at: atDays(-2),
    accepted_at: atDays(-1),
  }),
  application('application-anna-training', 'offer-kindertraining', DEMO_IDS.helper, {
    status: 'accepted',
    motivation_text: 'Ich kann das Kindertraining regelmäßig unterstützen.',
    helper_message: 'Ich freue mich auf die erste Einheit.',
    submitted_at: atDays(-7),
    accepted_at: atDays(-5),
  }),
  application('application-anna-tafel', 'offer-tafel', DEMO_IDS.helper, {
    status: 'shortlisted',
    motivation_text: 'Ich kenne die Abläufe bei Ausgaben und helfe auch beim Packen.',
    submitted_at: atDays(-3),
  }),
  application('application-anna-cleanup', 'offer-cleanup', DEMO_IDS.helper, {
    status: 'rejected',
    motivation_text: 'Ich wäre gerne beim Cleanup dabei.',
    submitted_at: atDays(-9),
    rejected_at: atDays(-7),
    organization_note: 'Das Team ist bereits vollständig.',
  }),
  application('application-anna-lesepaten', 'offer-lesepaten', DEMO_IDS.helper, {
    status: 'withdrawn',
    motivation_text: 'Ich lese Kindern sehr gerne vor.',
    submitted_at: atDays(-11),
    withdrawn_at: atDays(-8),
  }),
  application('application-anna-seniorencafe', 'offer-seniorencafe', DEMO_IDS.helper, {
    status: 'completed',
    motivation_text: 'Ich habe Erfahrung in der Betreuung älterer Gäste.',
    submitted_at: atDays(-35),
    accepted_at: atDays(-30),
    completed_at: atDays(-18),
  }),
  application('application-anna-kueche', 'offer-kuechenteam', DEMO_IDS.helper, {
    status: 'accepted',
    motivation_text: 'Ich kann morgen in der Küche unterstützen.',
    helper_message: 'Ich bin pünktlich vor Ort.',
    submitted_at: atDays(-2),
    accepted_at: atDays(-1),
  }),
  application('application-clara-webseite', 'offer-webseite', DEMO_IDS.helperClara, {
    status: 'completed',
    motivation_text: 'Ich übernehme die Übersetzung gerne und habe Erfahrung damit.',
    submitted_at: atDays(-35),
    accepted_at: atDays(-34),
    completed_at: atDays(-20),
  }),
];

export const conversations: ConversationRow[] = [
  {
    id: 'conversation-anna-sommerfest',
    application_id: 'application-anna-sommerfest',
    offer_id: 'offer-sommerfest',
    helper_profile_id: DEMO_IDS.helper,
    organization_profile_id: DEMO_IDS.org,
    last_message_at: atDays(0, 8),
    created_at: atDays(-1),
    updated_at: atDays(0, 8),
  },
  {
    id: 'conversation-bernd-sommerfest',
    application_id: 'application-bernd-sommerfest',
    offer_id: 'offer-sommerfest',
    helper_profile_id: DEMO_IDS.helperBernd,
    organization_profile_id: DEMO_IDS.org,
    last_message_at: atDays(0, 7),
    created_at: atDays(-2),
    updated_at: atDays(0, 7),
  },
  {
    id: 'conversation-anna-training',
    application_id: 'application-anna-training',
    offer_id: 'offer-kindertraining',
    helper_profile_id: DEMO_IDS.helper,
    organization_profile_id: DEMO_IDS.org,
    last_message_at: atDays(-2, 18),
    created_at: atDays(-7),
    updated_at: atDays(-2),
  },
  {
    id: 'conversation-anna-tafel',
    application_id: 'application-anna-tafel',
    offer_id: 'offer-tafel',
    helper_profile_id: DEMO_IDS.helper,
    organization_profile_id: DEMO_IDS.orgBunteStadt,
    last_message_at: atDays(-1, 16),
    created_at: atDays(-3),
    updated_at: atDays(-1),
  },
  {
    id: 'conversation-anna-kueche',
    application_id: 'application-anna-kueche',
    offer_id: 'offer-kuechenteam',
    helper_profile_id: DEMO_IDS.helper,
    organization_profile_id: DEMO_IDS.orgBunteStadt,
    last_message_at: atDays(0, 9),
    created_at: atDays(-2),
    updated_at: atDays(0, 9),
  },
];

export const messages: MessageRow[] = [
  {
    id: 'message-sommerfest-1',
    conversation_id: 'conversation-anna-sommerfest',
    sender_profile_id: DEMO_IDS.helper,
    body: 'Hallo, ich habe mich gerade beworben – gibt es noch offene Fragen?',
    status: 'read',
    read_at: atDays(0, 7),
    created_at: atDays(-1, 18),
    updated_at: atDays(0, 7),
  },
  {
    id: 'message-sommerfest-2',
    conversation_id: 'conversation-anna-sommerfest',
    sender_profile_id: DEMO_IDS.org,
    body: 'Hi Anna, danke für die Bewerbung! Wir melden uns spätestens morgen.',
    status: 'sent',
    read_at: null,
    created_at: atDays(0, 8),
    updated_at: atDays(0, 8),
  },
  {
    id: 'message-bernd-1',
    conversation_id: 'conversation-bernd-sommerfest',
    sender_profile_id: DEMO_IDS.org,
    body: 'Hallo Bernd, deine Erfahrung in der Logistik wäre super – bitte um 7 Uhr da sein.',
    status: 'sent',
    read_at: null,
    created_at: atDays(0, 7),
    updated_at: atDays(0, 7),
  },
  {
    id: 'message-training-1',
    conversation_id: 'conversation-anna-training',
    sender_profile_id: DEMO_IDS.helper,
    body: 'Danke für die Zusage, ich bin nächste Woche dabei.',
    status: 'read',
    read_at: atDays(-2),
    created_at: atDays(-3),
    updated_at: atDays(-2),
  },
  {
    id: 'message-training-2',
    conversation_id: 'conversation-anna-training',
    sender_profile_id: DEMO_IDS.org,
    body: 'Super, wir haben dich eingeplant. Treffpunkt ist direkt am Vereinsheim.',
    status: 'read',
    read_at: atDays(-2),
    created_at: atDays(-2, 18),
    updated_at: atDays(-2),
  },
  {
    id: 'message-tafel-1',
    conversation_id: 'conversation-anna-tafel',
    sender_profile_id: DEMO_IDS.orgBunteStadt,
    body: 'Hallo Anna, wir haben dich in die Vorauswahl genommen und melden uns mit Details.',
    status: 'sent',
    read_at: null,
    created_at: atDays(-1, 16),
    updated_at: atDays(-1),
  },
  {
    id: 'message-kueche-1',
    conversation_id: 'conversation-anna-kueche',
    sender_profile_id: DEMO_IDS.orgBunteStadt,
    body: 'Danke für deine Zusage. Treffpunkt ist morgen am Seiteneingang des Stadtteiltreffs.',
    status: 'sent',
    read_at: null,
    created_at: atDays(0, 9),
    updated_at: atDays(0, 9),
  },
];

export const notifications: NotificationRow[] = [
  {
    id: 'notification-message',
    recipient_profile_id: DEMO_IDS.helper,
    type: 'message',
    title: 'Neue Nachricht vom SV Sonnenschein e.V.',
    body: 'Danke für deine Bewerbung! Wir melden uns spätestens morgen.',
    entity_type: 'conversation',
    entity_id: 'conversation-anna-sommerfest',
    read_at: null,
    created_at: atDays(0, 8),
  },
  {
    id: 'notification-shortlist',
    recipient_profile_id: DEMO_IDS.helper,
    type: 'application.shortlisted',
    title: 'In der Vorauswahl',
    body: 'Deine Bewerbung für „Tafel-Ausgabe am Freitag“ ist in der engeren Auswahl.',
    entity_type: 'application',
    entity_id: 'application-anna-tafel',
    read_at: null,
    created_at: atDays(-1),
  },
  {
    id: 'notification-reminder',
    recipient_profile_id: DEMO_IDS.helper,
    type: 'assignment.reminder.24h',
    title: 'Morgen ist dein Einsatz',
    body: 'Dein Einsatz im Küchenteam beginnt morgen. Bitte prüfe Treffpunkt und Uhrzeit.',
    entity_type: 'application',
    entity_id: 'application-anna-kueche',
    read_at: null,
    created_at: atDays(0, 10),
  },
  {
    id: 'notification-application',
    recipient_profile_id: DEMO_IDS.org,
    type: 'application.submitted',
    title: 'Neue Bewerbung',
    body: 'Anna Helferin hat sich auf „Aufbau Sommerfest“ beworben.',
    entity_type: 'application',
    entity_id: 'application-anna-sommerfest',
    read_at: null,
    created_at: atDays(-1),
  },
];

export const savedOffers: SavedOfferRow[] = [
  {
    id: 'saved-kindertraining',
    helper_profile_id: DEMO_IDS.helper,
    offer_id: 'offer-kindertraining',
    created_at: atDays(-6),
  },
  {
    id: 'saved-tafel',
    helper_profile_id: DEMO_IDS.helper,
    offer_id: 'offer-tafel',
    created_at: atDays(-2),
  },
];

export const helperDocuments: HelperDocumentRow[] = [
  {
    id: 'document-anna-first-aid',
    helper_profile_id: DEMO_IDS.helper,
    document_type: 'certificate',
    status: 'active',
    title: 'Erste-Hilfe-Nachweis',
    description: 'Fiktiver Nachweis für die Portfolio-Demo.',
    storage_bucket: 'demo-only',
    storage_path: 'not-a-real-file',
    mime_type: 'application/pdf',
    file_size_bytes: 245_678,
    issued_at: dateOnly(-90),
    expires_at: dateOnly(275),
    created_at: atDays(-90),
    updated_at: updatedAt,
  },
];
